### ISSUE TITLE
Error executing command "codegen theme MyFirstTheme"

### ISSUE THREAD

**Issue by guaicaiboshi** [OrchardCMS/OrchardDoc#147]
orchard> codegen theme MyFirstTheme

Error executing command "codegen theme MyFirstTheme"
--------------------------------------------------------------------------------

No command found matching arguments "codegen theme MyFirstTheme". Commands avail
able: site setting set baseurl,autoroute create,theme list,theme activate,layer
create,widget create,menuitem create,menu create,blog create,blog import,blog bu
ild archive,user create,role list,role detail,permission list,user roles,user ad
d role,user remove role,role add permission,role remove permission,role create,r
ole delete,feature list,feature enable,feature disable,package create,package in
stall,package uninstall,page create,recipes harvest,recipes execute,warmup gener
ate,cultures list,cultures get site culture,cultures set site culture,cultures a
dd,help commands,help.

--------------------------------------------------------------------------------

**Comment by chanzig** [comment]
Are you sure  enabled code generation.
To enable code generation, click Features under Modules, find the Code Generation feature, and click Enable.

**Comment by abhishekluv** [comment]
Hello,

The OrchardDoc repo is only used to add/modify the content of the help docs. The Orchard community is the best place to look for help. https://orchard.codeplex.com/discussions
Thank you!

**Comment by emfluenceindia** [comment]
Hi,
I hope my issue is OK to post here. I am watching your video tutorial series on Theme development on Youtube. I placed my comment at https://www.youtube.com/watch?v=XvJOm22J39s&index=4&list=PL8AwaH3ssiARImeICwvOavU_Gna-Xza_7. The issue is I am not being able to create a Theme skeleton using codegen. It says `Command codegen doesn't exist`. Your help is greatly appreciated! Thank you.

**Comment by sandsad** [comment]
To enable code generate and try again command
