### ISSUE TITLE
multitenant format every thing!

### ISSUE THREAD

**Issue by matrix69** [OrchardCMS/OrchardDoc#157]
Hi
we use three tenant for our web site and implement it but our biggest problem is that tenants failed automatically and we have to reset IIS and delete cashe.cab. this solves the problem temporary but the problem happens again and agian. by reviewing the logs we understand that this happens when orchard-error.txt is made but it is empty.
is there any thing that we can do to solve the problem?
thank you in advance.

**Comment by abhishekluv** [comment]
Hello,

The OrchardDoc repo is only used to add/modify the content of the help docs. The Orchard community is the best place to look for help. https://orchard.codeplex.com/discussions
Thank you!
