### ISSUE TITLE
Messaging Node in Workflow missing

### ISSUE THREAD

**Issue by oneleft** [OrchardCMS/OrchardDoc#162]
I have installed and enabled the Messaging module and Email Messaging module.  I have also set the email settings and testing them with a Contact Us form.  

I am now trying to create a workflow that messages me when a comment is created, but there is no "Messaging" action node available in the Workflow toolbox.

What am I missing?

**Comment by bleroy** [comment]
Please ask such questions on the forum, or on Orchard Pros. This is the bug database for the documentation.
You need to enable "email workflow activities". Then'you'll have a "send email" activity.
