### ISSUE TITLE
commandline codegen theme does not exist

### ISSUE THREAD

**Issue by pungggi** [OrchardCMS/OrchardDoc#164]
I tryied to http://docs.orchardproject.net/Documentation/Customizing-the-default-theme
but the suggested command "codegen theme" doesnt seem to exist.

![image](https://cloud.githubusercontent.com/assets/5635709/8031901/5f8c09e4-0dd2-11e5-8113-7552dfb9d172.png)

**Comment by agriffard** [comment]
Have you enabled the 'Code Generation' feature?

**Comment by agriffard** [comment]
You must specify the name of the the theme you want to generate :
codegen theme MyTheme
