### ISSUE TITLE
Theme Includes Out of Date - Orchard Documentation 

### ISSUE THREAD

**Issue by adilhraza** [OrchardCMS/OrchardDoc#165]
It is probably good idea to add Last Updated: DateTimeStamp on the documentation pages :) , i mean when was the last time this page was updated?
http://docs.orchardproject.net/Documentation/themes-includes#HtmlZone("head""metasstylesscripts")

**Comment by abhishekluv** [comment]
Hi Adil,

Thanks. The above link is for theme creation using .aspx engine it shouldn't be online. 

Please refer to the "Creating Themes" section in the documentation for creating your own themes.

**Comment by adilhraza** [comment]
Cool
