### ISSUE TITLE
Two calls Html.Title affects each other

### ISSUE THREAD

**Issue by musukvl** [OrchardCMS/OrchardDoc#166]
Code sample:
```
@{
	string title = "Title";
	string siteName = "Site";
}
<meta property="og:title" content="@Html.Title(T(title).ToString(), T(siteName).ToString())" />
<title>@Html.Title(T(title).ToString(), T(siteName).ToString())</title>
```
makes:
```
 <meta property="og:title" content="Site - Title" />
 <title>Site - Title - Site - Title</title>
```

Because @Html.Title reuses same instance of IPageTitleBuilder. So PageTitleBuilder.AddTitleParts collects title parts for all @Html.Title calls.

For Orchard CMS 1.8.2

**Comment by abhishekluv** [comment]
This is the bug database for the documentation.

Please ask such questions here : https://github.com/OrchardCMS/Orchard/issues

**Comment by musukvl** [comment]
Thanks, I moved it to /OrchardCMS/Orchard/issues
so you can delete this task.
