### ISSUE TITLE
The Page for submitting pull requests is outdated

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/OrchardDoc#167]
Here
http://docs.orchardproject.net/Documentation/Contributing-patches

It still refer to codeplex 
"Once this is done, your changes are on CodePlex, but not yet in the project's official repository. To get it there, you'll need to ask us to pull the changes in. In order to do that, send us a pull request from the fork management screen under the source control tab on CodePlex:"

The global process seems Ok, but is it really Ok with Github. May be conventions on referencing issues are outdated ?

**Comment by rtpHarry** [comment]
FYI I am currently working on this
