### ISSUE TITLE
placement.info documentation should include information about global vs local zones

### ISSUE THREAD

**Issue by mwentz** [OrchardCMS/OrchardDoc#170]
As stated in the answer to this StackOverflow article http://stackoverflow.com/questions/14826212/blog-zone-placement placing a / before the zone name in the Place element renders the shape in the global zone as opposed to the local zone. This is a pretty crucial feature that should be included in the "Understanding placement info" documentation.

**Comment by abhishekluv** [comment]
Thanks @mwentz. I'll update it.

**Comment by rtpHarry** [comment]
Actually, after coming a cropper to this little issue today I checked the documentation and it does cover it.

A pull request was accepted about 5 months ago which changed it (https://github.com/OrchardCMS/OrchardDoc/commit/2ea6a910b805f388fcb36a801f264bd474d69335).

The page could do with some love as it doesn't mention the `SummaryAdmin` display type and the way it covers the options would be better suited to a specification type table I think.
