### ISSUE TITLE
After deleting content picker field from content type, the projection data that was added by that content picker still shows on the site

### ISSUE THREAD

**Issue by alexstasyuk** [OrchardCMS/OrchardDoc#171]
Hello,

I have created a custom content type and added a content picker field to it.  Then I created a query and projection and added that projection to the custom content via content picker.  I am trying to get rid of it, but it doesn't go away.  I deleted the projection and query, and the content picker field from the custom content type but the data is still showing in the front end of the website.  Is this a bug of some sort?  Or I cannot delete these things?  Thank you for any help.

**Comment by abhishekluv** [comment]
This is the bug database for the documentation.

Please ask such questions here : https://github.com/OrchardCMS/Orchard/issues
