### ISSUE TITLE
Missing database schema info for new users

### ISSUE THREAD

**Issue by mushu999** [OrchardCMS/OrchardDoc#173]
http://docs.orchardproject.net/Documentation/Manually-installing-Orchard-zip-file

This page should have a link to an area that describes the table layout for the database setup that is needed. I'm a new user trying it out to see if we are interested in using it (along with DNN and a few other CMS's). I have existing IIS and SQL Server boxes and will be trying to move over our existing website. I'm partway through the install instructions but then hit the database setup section. Without knowing how to set up the database I'm stuck.

Sorry if this is the wrong area for this post.

**Comment by bleroy** [comment]
What do you need the table layout for? It's not fixed and can't be documented that way: any module can create new tables.

**Comment by mushu999** [comment]
Ok thanks. I just think it needs more info related to people that have SQL Server and IIS already installed. For example, saying that the app will create tables as needed would have been helpful so I wasn't searching for the schema to create beforehand, especially since the page said that the database needs to be created before the installation of Orchard.

**Comment by bleroy** [comment]
Fair enough, that's a good point.
