### ISSUE TITLE
Site Powered By AppHarbor In Footer

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/OrchardDoc#175]
The docs footer currently has this link in it which seems out of date:

![image](https://cloud.githubusercontent.com/assets/1038062/9506465/3c037e4c-4c40-11e5-921c-cb0255da6ad7.png)

Can anyone confirm this is no longer the case so I can make a pull request for it?

**Comment by abhishekluv** [comment]
Is it? The AppHarbor link is working fine. I think the OrchardDoc repo is hosted at AppHarbor.

**Comment by rtpHarry** [comment]
Ah ok I did mean is it currently hosted at AppHarbor.

While I've been getting familiar the project I've been poking around in all corners of the repos and I noticed that the main Orchard site didn't have this link so I thought maybe it was just out of date.
