### ISSUE TITLE
'not authenticated' layers not being rendered

### ISSUE THREAD

**Issue by d3v3l0p3r** [OrchardCMS/OrchardDoc#204]
Since upgrading to Orchard 1.9.1 we now have no footer information on our login page when a user is unauthenticated.

It is no longer being rendered. If i set the 'layer rule' to 'authenticated' the footer is rendered.

This is because the Model.Footer is now null in our custom Layout.cshtml

Any suggestions from anyone please?

**Comment by rtpHarry** [comment]
You have posted this in the wrong place mate. This is the repo for the documentation.

If you're reporting a bug you can use [the official repo issues](https://github.com/OrchardCMS/Orchard/issues).

If you're wanting to open a discussion / get support then there are [support forums on codeplex](https://orchard.codeplex.com/discussions).

**Comment by d3v3l0p3r** [comment]
ok sorry mate, will close and reopen on the correct repo!. cheers
