### ISSUE TITLE
Integrate the concept of squashing PRs down to a single commit into the docs

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/OrchardDoc#234]
The documentation should make it clear that you need to squash your commits to keep things clean.  It looks like when the repo was on CodePlex this was handled by the team.

The "contributing patches" has a [mention of it](http://docs.orchardproject.net/Documentation/Contributing-patches#Pullrequestreviewprocess) which needs amending and cross linking to "merging pull requests".

The "merging pull requests" needs to be updated for GitHub and made clear that it's the developer that creates the PR that needs to keep their branch clean.

  - http://docs.orchardproject.net/Documentation/Contributing-patches
  - http://docs.orchardproject.net/Documentation/Merging-Pull-Requests

**Comment by rtpHarry** [comment]
When podcast Tuesday 23rd Feb 2016 is published on YouTube then add a link to this at around 51 minutes deep.

Sebastienros did a video presentation explaining how to do the squash without having to use the cumbersome squash ui (you do a reset branch back to the first commit and then choose the mixed mode so it keeps your changes, then you can commit everything again in one go and the history to keep it clean)

**Comment by rtpHarry** [comment]
Video is here:

  * https://youtu.be/Dq6iagiOXiw?t=51m19s

**Comment by agriffard** [comment]
GitHub now allow to squash PR automatically on merge.
