### ISSUE TITLE
Rename a contentPartRecord

### ISSUE THREAD

**Issue by sohaibjaved44** [OrchardCMS/OrchardDoc#244]
HI, 
I'm facing issue when I rename a content part Record class. name of my contentPart class was displayLinksPartRecord I updated it to displayLink_PartRecord so it created a table with this name "displayLink_PartRecord" and then updated back to displayLinksPartRecord  and it started throwing exception onload with message "invalid object name displayLinksPartRecord"

**Comment by rtpHarry** [comment]
I'm not sure the exact answer but I would recommend posting this on StackOverflow.com with a #orchardcms tag.

I know a lot of the main developers are active on their but they don't really monitor this repo. This is for issues with the documentation project that supports Orchard CMS not the actual CMS itself.
