### ISSUE TITLE
Builtin features page - deprecate Orchard.jQuery and document Orchard.Resources

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/OrchardDoc#254]
http://docs.orchardproject.net/Documentation/Builtin-Features#OrchardjQuery

Mark this as deprecated as of 1.10. Recommend migration to Orchard.Resources.

Add an Orchard.Resources section with a brief description and note added in 1.10.

**Comment by BullShinkles** [comment]
Many modules are still broken... you offer no backward support?  Is Orchard dying a dumb death for the sake of progress?
