### ISSUE TITLE
orchard manual install fails with named SQL Server instance 

### ISSUE THREAD

**Issue by jemrelay** [OrchardCMS/OrchardDoc#257]
Using the Orchard.Web.1.9.2.zip distribution, I get a  "Object reference not set to an instance of an object" if I try connecting to a named SQL Serve 2012 Enterprise instance. When I use a default instance, the install works fine.

**Comment by rtpHarry** [comment]
Hi, just thought I would point out that you have opened this issue in the wrong place. This repo is for issues relating to the documentation website for Orchard.

  * If you want to report a bug in Orchard then you should [open an issue here](https://github.com/OrchardCMS/Orchard/issues).
  * If you need help with something that you're confused about your best bet is either to ask a question on StackOverflow with the [OrchardCMS tag](http://stackoverflow.com/questions/tagged/orchardcms) or start a discussion in the [official Orchard forums](https://orchard.codeplex.com/discussions).
