### ISSUE TITLE
Retrive RoleName according username on layout.cshtml for custom header masterpage in Orchard cms

### ISSUE THREAD

**Issue by yasirriazawan** [OrchardCMS/OrchardDoc#258]
Retrive RoleName according username on layout.cshtml for custom header masterpage in Orchard cms

**Comment by rtpHarry** [comment]
Hi, are you asking a question or suggesting a topic for the Orchard documentation website?

**Comment by agriffard** [comment]
Wrong repo. Use https://github.com/OrchardCMS/Orchard
