### ISSUE TITLE
[RTD] initial notes

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/OrchardDoc#268]
I made these notes while I was doing some initial investigation of the rtd branch. Posting here unedited for the moment:

## Notes

Code formatting - can we make it any prettier, seems quite plain

The umbrella page for my getting started with modules course is replaced with just a toc. I put it in as the first item in the toc but its not showing up in the menu, not sure if this is a clash

We need to set up sitewide 301 redirects for old urls to new .html extension

Need to style the block quotes to have some kind background as articles written expecting it and now the `>` quotes just blend in with the text.

put one line or half line margin under each `<li>`

put a stroke around the images as they are mostly partial screenshots so just makes it neater as the image cuts off (in current docs site)

zip downloads are 404 - need to be moved to another storage location unless we can include them in the rtd build?

table to check fixed on line 294 of getting started with modules part 4

build error:

    WARNING: html_static_path entry 'E:\\rtpSoftware\\OrchardDocs\\OrchardDoc\\docs\\_static' does not exist

**Comment by rtpHarry** [comment]
@agriffard fyi

**Comment by agriffard** [comment]
I added files in docs\_static. You should be able to retrieve it.

**Comment by rtpHarry** [comment]
I've split these all out into individual issues now so anyone can tackle them.
