### ISSUE TITLE
[RTD] don't break existing links in new site

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/OrchardDoc#275]
I think that the redirect features in RTD will let us launch the new site without breaking the old structure.

I don't have access to the RTD account, @agriffard can you try this for me please?

Set the redirects to this in the admin panel:

![image](https://cloud.githubusercontent.com/assets/1038062/14869533/ee8d84b2-0ccb-11e6-9410-60dc8a8ac91c.png)

This should then mean that for example this url (neither of these links will work at the moment they are examples):

http://docs.orchardproject.net/Documentation/Getting-Started-with-Modules-Part-1

Will forward to this url:

http://docs.orchardproject.net/en/rtd/Documentation/Getting-Started-with-Modules-Part-1

Please can you let me know how it turns out.

If it works and does forward old urls to new url structure then we would need to go back through the RTD branch and remove the `.html` you have put in on all the internal links but this small amount of effort would be worth it if we can save the link structure.

**Comment by agriffard** [comment]
I tried to add a .htaccess file with a redirect rule to the .html but it doesn't seem to work, while the .htaccess is there.

**Comment by agriffard** [comment]
I added the redirection 'Redirect: Sphinx HTMLDir -> HTML' but it doesn't work.
