### ISSUE TITLE
[RTD] get published branches set up correctly

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/OrchardDoc#276]
The "latest" branch is 404 at the moment when viewed on RTD

We also need to specify a version tag for 1.10 I think? Unless it's done after the we start on the next version.

I think that we should also create a "legacy" version of docs so that the old docs are preserved but we can do some proper clean up on the 1.10 branch (after launch) -- what are our version options when creating branches in rtd?

**Comment by agriffard** [comment]
OK, A branch with the version '1.10' could also be created.

We will create a 'legacy' branch based on the master before to merge the rtd branch to the latest.

ReadTheDocs allows to specify which branches have to be built.

**Comment by agriffard** [comment]
'legacy' branch created.
