### ISSUE TITLE
[RTD] all .zip files seem to be broken at the moment

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/OrchardDoc#277]
For example the last line on:

http://orcharddoc.readthedocs.org/en/rtd/Documentation/Building-a-hello-world-module.html

Need to figure out if its the path or if it is the platform not supporting binary downloads.

**Comment by agriffard** [comment]
Fixed adding html_extra_path = ['Attachments/Building-a-hello-world-module/HelloWorld.zip'] in conf.py.

Still need to fix other links to .zip files.

**Comment by agriffard** [comment]
Using MkDocs, any file link will be recognized.
