### ISSUE TITLE
[RTD] incorporate the orchard logo

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/OrchardDoc#278]
there is an admin option to inject a logo into the skin

**Comment by agriffard** [comment]
Do you have an example?

**Comment by agriffard** [comment]
http://read-the-docs.readthedocs.io/en/latest/custom_installs/customization.html

**Comment by agriffard** [comment]
I added the favicon.
A link to the main site orchardproject.net could also be added.
