### ISSUE TITLE
Not found page shows error too many redirects

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/OrchardDoc#290]
I was searching Google for "orchard cms user roles" and it came up with this url:

  * http://docs.orchardproject.net/en/latest/Documentation/users/

which appears to be some old spec documentation but it's not on the new site, anyway that resulted in this:

![image](https://cloud.githubusercontent.com/assets/1038062/15469071/c4f2c964-20df-11e6-9af3-f79440a1a384.png)

Testing with any broken url brings the same situation:

  * http://docs.orchardproject.net/en/latest/Documentation/Understanding-perghfghfmissions/

**Comment by agriffard** [comment]
The urls are case sensitive : http://docs.orchardproject.net/en/latest/Documentation/Users/ works.
