### ISSUE TITLE
release notes to orchard 1.8.2 is broken

### ISSUE THREAD

**Issue by roballred** [OrchardCMS/OrchardDoc#292]
I am looking into upgrading a busy site from 1.8.1 to 1.9.3 or i would have never found this. In the release notes for 1.9
http://docs.orchardproject.net/en/latest/Documentation/Orchard-1-9.Release-Notes/

links to the instructions in 1.8.2 with the following url

http://docs.orchardproject.net/en/latest/Documentation/orchard-1-8-2.release-Notes

but then is redirected or something to the following link
http://docs.orchardproject.net/en/latest///////////////////////////////////////////Documentation/orchard-1-8-2.release-Notes

which doesn't work for obvious reason.

**Comment by rtpHarry** [comment]
Good spot, I've fixed the release notes link.

**Comment by agriffard** [comment]
Note for your next fix @rtpHarry : you can add to your commit message 'fix #issuenumber' to make it closed automatically.
https://help.github.com/articles/closing-issues-via-commit-messages/
