### ISSUE TITLE
ContentPart attribute is not included in placement.info documentation

### ISSUE THREAD

**Issue by flew2bits** [OrchardCMS/OrchardDoc#299]
From what I can tell, the ContentPart attribute has been available for the Match element in placement.info since Orchard 1.7.2, but there is no documentation on it. I've made an update to the documentation and will submit a PR shortly.

**Comment by rtpHarry** [comment]
Thanks, I try to make a note of the version that it changed so if you could work the v1.7.2 in to the wording that would be great.

**Comment by rtpHarry** [comment]
Fixed with #300
