### ISSUE TITLE
Broken Themes Link 

### ISSUE THREAD

**Issue by ponarunkumar** [OrchardCMS/OrchardDoc#312]
On the page, http://docs.orchardproject.net/en/latest/Documentation/Walkthroughs/ links under themes are broken.
![image](https://cloud.githubusercontent.com/assets/6130502/19830318/64956692-9dc3-11e6-8646-647a1a4e134e.png)

**Comment by agriffard** [comment]
Sorry those html pages are not in the documentation anymore.
