### ISSUE TITLE
The Orchard.Azure.DatabaseCache configuration settings are missing or invalid.

### ISSUE THREAD

**Issue by philipacrowe** [OrchardCMS/OrchardDoc#313]
Hello, I'm trying to make a local instance use my azure db. When i use the settings.txt from my live instance i see a 404 page and this error about azure cache in the app_data logs. Can I disable the azure cache on the local instance?

The Orchard.Azure.DatabaseCache configuration settings are missing or invalid.

**Comment by DanielStolt** [comment]
This is the documentation repo - please use the forums instead for community support questions, or if you believe there is a bug in the code, the OrchardCMS/Orchard repo.
