### ISSUE TITLE
https://orchardcore.readthedocs.io/en/dev/docs/guides/decoupled-cms/decoupled/

### ISSUE THREAD

**Issue by captmomo** [OrchardCMS/OrchardDoc#357]
The link to building a decoupled CMS gives a 404.

**Comment by Piedone** [comment]
Well, I just noticed this :). The correct URL, linked from within the docs site, is this: https://docs.orchardcore.net/en/dev/docs/guides/decoupled-cms/

Also, this project is about the Orchard 1.x. docs.
