### ISSUE TITLE
Localization.Culture filter does not work

### ISSUE THREAD

**Issue by PogudinaAnnaYu** [OrchardCMS/OrchardDoc#359]
Hi! 
We use "OrchardCore.Application.Cms.Targets" Version="1.0.0-rc1-12653" and
"OrchardCore.Translations.ru" Version="1.0.0-rc1-105368"
We have a dictionary which has fields: title and localization.  We get an error when we make query in GraphQl with filter by Localization.Culture.
Query which we make: 
```
query MyQuery {
  localizationDictionary(where: {localization: {localizationSet: "", culture: "ru"}}) {
    localization {
      culture
      localizationSet
    }
    displayText
  }
}
```
Answer from server which we get (error message translated from Russian): 
```
"extensions": {
        "code": "POSTGRES",
        "data": {
          "Severity": "ERROR",
          "InvariantSeverity": "ERROR",
          "SqlState": "42703",
          "MessageText": "column LocalizedContentItemIndex.culture is not found",
          "Hint": "Perhaps a column reference was supposed \"LocalizedContentItemIndex.Culture\".",
          "Position": 385,
          "File": "d:\\pginstaller.auto\\postgres.windows-x64\\src\\backend\\parser\\parse_relation.c",
          "Line": "3294",
          "Routine": "errorMissingColumn"
        }
      }
```

Do you know what is the problem?

**Comment by Skrypt** [comment]
That's a duplicate. Issue is related with PostgreSQL case sensitivity.
The correct column name is LocalizedContentItemIndex.Culture
