### ISSUE TITLE
Running TheBlog Theme Recipe Removes Built-In Form Feature

### ISSUE THREAD

**Issue by RaisinBread42** [OrchardCMS/OrchardDoc#360]
Would like to do more testing on this to find the full scope and cause of the issue, but don't think I have the knowledge to do that.  What I was able to do was, which didn't work:

- Disable and Enable the form feature
- Changing theme (but didn't run the recipe).  Slight digress, but would've imagined there would be a feature to undo changes made by recipes ?

**Comment by agriffard** [comment]
Wrong repository, please use https://github.com/OrchardCMS/OrchardCore
