### ISSUE TITLE
Add the ability for users to comment on the documentation.

### ISSUE THREAD

**Issue by shaunluttin** [OrchardCMS/OrchardDoc#87]
- Justin said he would work on this.
- We spoke about this at Orchard Harvest 2014.
- We talked about using Disqus: http://disqus.com/
- We talked about using Discourse http://www.discourse.org/

**Comment by rtpHarry** [comment]
The last time I heard this talked about in the weekly meeting it was said that the docs are easy enough to edit if you have something to contribute so the comments aren't required.

Can this be closed?
