### ISSUE TITLE
Improve the layout and design of the docs site.

### ISSUE THREAD

**Issue by shaunluttin** [OrchardCMS/OrchardDoc#89]
This is the strategy we talked about at Orchard Harvest:
1. Create PDF mockup for orchardproject.net. Done.
2. Create HTML mockup based on PDF.
3. Create Orchard CMS theme based on HTML mockup.
4. Deploy that theme for orchardproject.net
5. Deploy that CSS and layout to the docs.orchardproject.net website.
6. Consider creating a userdocs.orchardproject.net website for content developers, which will also use that CSS and layout.

Here is a diagram of the end result. Note: orchardproject.net is an Orchard CMS; the docs sites are not. The docs sites receive their content from GitHub repos.

![capture](https://cloud.githubusercontent.com/assets/2066637/3260861/66caa932-f252-11e3-9a79-40e4a856df12.PNG)

**Comment by agriffard** [comment]
read the docs is now used with a default theme.
